### ISSUE TITLE
Sorry, only users with push access can use that command

### ISSUE THREAD

**Issue by skjnldsv** [ahmadnassri/action-dependabot-auto-merge#11]
![Capture d’écran_2020-09-04_13-36-39](https://user-images.githubusercontent.com/14975046/92235272-ad2a2b00-eeb3-11ea-9293-58ea73b811cb.png)

But i'm using a personal token  :thinking: 

```yml
name: Dependabot
on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v1
    with:
      target: patch
      github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}

```
