### ISSUE TITLE
Merge not merging

### ISSUE THREAD

**Issue by cujarrett** [ahmadnassri/action-dependabot-auto-merge#112]
## What

I am trying to set up auto merge in one of my repos and seeing it almost work but then not merge.

My config:

```yml
name: auto-merge

on: [pull_request_target]

jobs:
  auto-merge:
    name: auto-merge
    needs: test
    runs-on: ubuntu-latest
    # Guarantee that commit comes from Dependabot (don't blindly trust external GitHub Actions)
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor # includes patch updates
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE_GH_TOKEN }}

```

Example PR: https://github.com/cujarrett/destiny-insights-bot/pull/230

I see things that look positive like

```
Dependabot will merge this PR once CI passes on it, as requested by @cujarrett.
```

and 

```
@dependabot merge
```

But the PR is still open.

@ahmadnassri - Any thoughts?
