### ISSUE TITLE
Error: Input required and not supplied: github-token

### ISSUE THREAD

**Issue by marckohlbrugge** [ahmadnassri/action-dependabot-auto-merge#124]
Any ideas why I might getting the following error?

`Error: Input required and not supplied: github-token`

I've followed the README example and set the github-token. My `automerge.yml` looks like this:

```yml
name: automerge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTOMERGE_GITHUB_TOKEN }}
```

The repo has a secret called `AUTOMERGE_GITHUB_TOKEN` with a Personal Access Token with full `repo` access.

When I manually re-run this action it succeeds.
