### ISSUE TITLE
HttpError: Not Found at /action/node_modules/@octokit/request

### ISSUE THREAD

**Issue by bennycode** [ahmadnassri/action-dependabot-auto-merge#128]
Hello, I am using your action in a private repo but it fails with this output:

> loaded merge config: 
> - match:
>     dependency_type: all
>     update_type: 'semver:minor'
> 
> title: "chore(deps): bump minimist from 1.2.5 to 1.2.6"
> depName: minimist
> from: 1.2.5
> to: 1.2.6
> dependency type: production
> security critical: false
> config: all:semver:minor
> all:semver:minor detected, will auto-merge
> Error: Not Found
> HttpError: Not Found
>     at /action/node_modules/@octokit/request/dist-node/index.js:66:[23](https://github.com/bennycode/lambot-1/runs/5664173033?check_suite_focus=true#step:4:23)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async approve (file:///action/lib/api.js:2:3)
>     at async default (file:///action/lib/index.js:31:5)
>     at async file:///action/index.js:53:1

Am I doing something wrong?

Here is my config:

**.github/auto-merge.yml**

```yml
- match:
    dependency_type: all
    update_type: 'semver:minor'
```

**.github/workflows/merge-dependencies.yml**

```yml
name: 'Merge Dependencies'

# https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
# https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60#issuecomment-806027389
on: [pull_request_target]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Automerge dependency updates from Dependabot'
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.GH_AUTOMERGE_TOKEN }}
```

Best,
Benny
