### ISSUE TITLE
Sorry, only users with push access can use that command.

### ISSUE THREAD

**Issue by rickyrauch** [ahmadnassri/action-dependabot-auto-merge#144]
Hello !

I know there are many issues related to this problem but still can't make it to work.

The repo is under our organization and I created the new token under my personal account.

<img width="1034" alt="Screen Shot 2022-05-24 at 11 02 39 AM" src="https://user-images.githubusercontent.com/197196/170102331-cbd46061-c693-4a15-a2d2-46fe878f7e70.png">

This is the output of the action:
<img width="1320" alt="Screen Shot 2022-05-24 at 11 06 36 AM" src="https://user-images.githubusercontent.com/197196/170102995-934da377-b1c3-4791-8958-d79fff2bdcb2.png">

Thanks!

**Comment by MerlinMason** [comment]
I'm struggling with the same issue too, also in a private organisation repo. I've given the job the following permissions
```
permissions:
  pull-requests: write
  contents: write
```
But also get the same automated comment back.

**Comment by dead-claudia** [comment]
Also making some noise as we're running into the same issue: https://github.com/MithrilJS/mithril.js/pull/2790#issuecomment-1163967946

First run failed due to what appears to be a flake: https://github.com/MithrilJS/mithril.js/runs/7006386076?check_suite_focus=true

**Comment by ahmadnassri** [comment]
apologies for delayed follow up, I've been dealing with personal issues and have not had time to help debug.

any community member help is more than appreciated.

though a quick hint would be to try using PAT (Personal Access Tokens) if you're blocked as I've found more success with those than the generated tokens by github. 

I'm hoping next week will be a time I can get some apace for myself to catch up on this and other projects

**Comment by finnSMB** [comment]
@rickyrauch @MerlinMason has any one of you two figured out a way to solve this? I am currently struggling with this issue too, private repo, not in an orga.

**Comment by MerlinMason** [comment]
@finnSMB no but yes... I ended up swapping to https://github.com/fastify/github-action-merge-dependabot with the following config which has been working great.

```
auto-merge:
        name: Auto-Merge PRs by Dependabot
        needs:
            - check-linting
            - check-dependencies
            - check-cypress
            - check-unit-tests
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
          - uses: fastify/github-action-merge-dependabot@v3.0.0
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                target: minor
```
