### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createReview')

### ISSUE THREAD

**Issue by maciejmakowski** [ahmadnassri/action-dependabot-auto-merge#166]
I am still in the process of further investigating what could have changed, but I thought I am going to post here in case anyone else has an idea.

As far as we know, nothing changed in the configuration of the token itself or the secret, but suddenly (around 12-24h ago) the setup that we had successfully working for months started failing with:
```
dependency type: production
security critical: false
config: production:semver:patch
production:semver:patch detected, will auto-merge
Error: Cannot read properties of undefined (reading 'createReview')
TypeError: Cannot read properties of undefined (reading 'createReview')
    at approve ([file:///action/lib/api.js:2:23](https://github.com/ahmadnassri/action-dependabot-auto-merge/blob/master/action/lib/api.js#L2))
    at default (file:///action/lib/index.js:31:11)
    at file:///action/index.js:[53](https://github.com/1debit/dependabot-test/actions/runs/3527941119/jobs/5919738455#step:4:54):7
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

The line in question is this:
```
  await octokit.pulls.createReview({
```

Which appears to mean that `octokit.pulls` is `undefined`, but also that it does not appear to be a permission issue as such with the token since it got that far.

At first I thought that something might have changed on the latest `2.6.1` release from earlier today, but I confirmed that the issue is also still happening with `2.6.0` which as I said before we've been using fine for months.

I am also sending this to Github support, but I was wondering whether anyone else has seen this and if yes, whether they found a solution for it.

Thanks in advance.

**Comment by mauriciabad** [comment]
Same here

**Comment by char0n** [comment]
I can confirm as well

**Comment by boboldehampsink** [comment]
Same here

**Comment by sdk1990** [comment]
Another one here.

**Comment by char0n** [comment]
For anybody looking for a solution for this problem. 

Here is how my workflow looked before (using this action):

```yaml
name: Merge me!

on:
  pull_request_target:

jobs:
  merge-me:
    name: Merge me!
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          command: squash and merge
```

Here is the replacement workflow which works exactly the same:

```yaml
name: Merge me!

on:
  pull_request_target:

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: github.actor == 'dependabot[bot]'
    steps:
      # This first step will fail if there's no metadata and so the approval
      # will not occur.
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # Finally, tell dependabot to merge the PR if all checks are successful
      - name: Instruct dependabot to squash & merge
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          allow-repeats: true
          message: |
            @dependabot squash and merge
        env:
          GITHUB_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
```
