### ISSUE TITLE
Action doesn't merge a bump from the correct target

### ISSUE THREAD

**Issue by Vincent-FundApps** [ahmadnassri/action-dependabot-auto-merge#18]
Hello,

I've moved to the v2.0.1 of your action and I'm getting now this strange behaviour.

The target is set to minor, however when it finds a minor upgrade it doesn't merge it and says `manual merging required`.

Could you please let me know what's wrong?

```
 Run ahmadnassri/action-dependabot-auto-merge@v2.0.13s
    approve: true
Run ahmadnassri/action-dependabot-auto-merge@v2.0.1
  with:
    target: minor
    github-token: ***
    command: merge
    approve: true
/usr/bin/docker run --name ahmadnassriactiondependabotautomergev2_7f5454 --label 3b3ac6 --workdir /github/workspace --rm -e INPUT_TARGET -e INPUT_GITHUB-TOKEN -e INPUT_COMMAND -e INPUT_APPROVE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/BucketNetting/BucketNetting":"/github/workspace" ahmadnassri/action-dependabot-auto-merge:v2
using workflow's "target": 
- match:
    dependency_type: all
    update_type: 'semver:minor'

title: "Bump @babel/preset-env from 7.4.4 to 7.11.5 in /js"
depName: @babel/preset-env
from: 7.4.4
to: 7.11.5
dependency type: production
security critical: false
manual merging required
```

**Comment by ahmadnassri** [comment]
hmmm interesting, can you share your workflow file and your `auto-merge.yml` (if you have one)

**Comment by ahmadnassri** [comment]
I believe `v2.0.2` has the hotfix that will address your issue.

upgrade to latest (`v2.0.4`) or simply use `v2` in your workflow: `ahmadnassri/action-dependabot-auto-merge@v2` to use the latest within the same major

**Comment by Vincent-FundApps** [comment]
Thanks @ahmadnassri 
I bumped the action 2.0.4 and it's approving and merging as a charm.

It's interesting to not that it the action got upgraded to 2.0.1 and not 2.0.4  by dependabot yesterday. Not too sure when you released v2.0.4 but maybe something to look into.

**Comment by ahmadnassri** [comment]
they were all released in sequence on the same day 

possibly, your dependabot config has a max number of PRs per day / week etc ... or it just derped 🤷‍♂️

regardless, that's a dependabot question I cannot answer

**Comment by bennyn** [comment]
I also [had a run](https://github.com/bennyn/coinbase-pro-node/pull/271/checks?check_run_id=1174767801) where I got messaged with "manual merging required". Upgrading the action from v1 to v2 helped.

Here is my final config:

**/.github/workflows/ci.yml**

```yml
      - name: 'Automerge dependency updates from Dependabot'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        # Guarantee that commit comes from Dependabot (don't blindly trust external GitHub action checks)
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GH_TOKEN }}
```

**/.github/auto-merge.yml**

```yml
- match:
    dependency_type: all
    update_type: 'semver:major'
```

**/.github/dependabot.yml**

```yml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    target-branch: master
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "type: chore \U0001F9F9"
```
