### ISSUE TITLE
Error: Nor found

### ISSUE THREAD

**Issue by macdrorepo** [ahmadnassri/action-dependabot-auto-merge#195]
Hello,

Can anyone can tell me what went wrong as I'm getting error as below:

> Run ahmadnassri/action-dependabot-auto-merge@v2
>   with:
>     target: minor
>     github-token: ***
>     config: .github/auto-merge.yml
>     command: merge
>     botName: dependabot
>     approve: true
> /usr/bin/docker run --name ghcrioahmadnassriactiondependabotautomerge266_09d58e --label ea425b --workdir /github/workspace --rm -e "INPUT_TARGET" -e "INPUT_GITHUB-TOKEN" -e "INPUT_CONFIG" -e "INPUT_COMMAND" -e "INPUT_BOTNAME" -e "INPUT_APPROVE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sonyhive_wowza-imagebuilder/sonyhive_wowza-imagebuilder":"/github/workspace" ghcr.io/ahmadnassri/action-dependabot-auto-merge:2.6.6
> using workflow's "target": 
> - match:
>     dependency_type: all
>     update_type: semver:minor
> 
> title: "Bump aws-cdk-lib from 2.54.0 to 2.61.0"
> depName: aws-cdk-lib
> from: 2.54.0
> to: 2.61.0
> dependency type: production
> security critical: false
> config: all:semver:minor
> all:semver:minor detected, will auto-merge
> Error: Not Found
> HttpError: Not Found
>     at /action/node_modules/@octokit/request/dist-node/index.js:86:21
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async approve (file:///action/lib/api.js:2:3)
>     at async default (file:///action/lib/index.js:33:5)
>     at async file:///action/index.js:53:1

My dependa config is minimal:
```
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "lambdasrc/layer/python/lib/python3.9/site-packages"
    schedule:
      interval: "weekly"
```
and my automerge flow:

```
name: auto-merge

on:
  workflow_dispatch:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.gh_token }}
```
