### ISSUE TITLE
Allow action to run based on a manuell trigger

### ISSUE THREAD

**Issue by DutchmanNL** [ahmadnassri/action-dependabot-auto-merge#22]
hi, thanks for this workflow I like it !
Would be nice to allow manual triggering the workflow currently that runs into an error ;

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/runs/1111509298?check_suite_focus=true#step:4:8

Example action definition for manual run :
```
on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
```
