### ISSUE TITLE
 failed to parse title: no recognizable versions

### ISSUE THREAD

**Issue by janisz** [ahmadnassri/action-dependabot-auto-merge#235]
```
title: "Bump actions/setup-go from 2 to 4"
depName: actions/setup-go
Warning: failed to parse title: no recognizable versions
```

- https://github.com/stackrox/helmtest/pull/29

**Comment by Noxillio** [comment]
I'm getting the same thing.

```
title: "Bump undici and discord.js"
depName: undici
Warning: failed to parse title: no recognizable versions
```

**Comment by nickmcdowall** [comment]
Also seeing this error on one of my projects.

Details of the action below:

```
Run ahmadnassri/action-dependabot-auto-merge@v2
/usr/bin/docker run --name ghcrioahmadnassriactiondependabotautomerge266_04b352 --label a3edf0 --workdir /github/workspace --rm -e "INPUT_TARGET" -e "INPUT_GITHUB-TOKEN" -e "INPUT_CONFIG" -e "INPUT_COMMAND" -e "INPUT_BOTNAME" -e "INPUT_APPROVE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/lsd-junit5/lsd-junit5":"/github/workspace" ghcr.io/ahmadnassri/action-dependabot-auto-merge:2.6.6
using workflow's "target": 
- match:
    dependency_type: all
    update_type: semver:major

title: "fix: bump the other-dependencies group with 8 updates"
depName: the
Warning: failed to parse title: no recognizable versions
```

**Comment by christofferbergj** [comment]
I'm seeing the same thing:

```
using workflow's "target": 
- match:
    dependency_type: all
    update_type: semver:minor

title: "Bump the react group with 1 update"
depName: the
Warning: failed to parse title: no recognizable versions
```

My `dependabot.yml` config has these groups:

```yml
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      pandacss:
        patterns:
          - '@pandacss*'
      storybook:
        patterns:
          - '@storybook*'
          - 'storybook*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
```
