### ISSUE TITLE
Target minor fails to automerge 2.0.0rc2 to 2.0.0rc3

### ISSUE THREAD

**Issue by woutervh** [ahmadnassri/action-dependabot-auto-merge#239]
using following config at
https://github.com/libranet/libranet-flask/blob/main/.github/workflows/dependabot-auto-merge.yaml
```
# see https://github.com/ahmadnassri/action-dependabot-auto-merge
name: Auto Merge Dependabot

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.TOKEN_AUTOMERGE }}
```

this fails to automerge on release-candidate  sphinx-rtd-theme from 2.0.0rc2 to 2.0.0rc3:
```
title: "Bump sphinx-rtd-theme from 2.0.0rc2 to 2.0.0rc3"
depName: sphinx-rtd-theme
from: 2.0.0
to: 2.0.0
dependency type: production
security critical: false
config: all:semver:minor
Warning: no version range detected in PR title
manual merging required
```
