### ISSUE TITLE
Should the workflow trigger be changed to pull_request_target?

### ISSUE THREAD

**Issue by AlCalzone** [ahmadnassri/action-dependabot-auto-merge#24]
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

There is a new trigger `pull_request_target` that allows to run actions in the base repo, even if the PR originates from a fork. This way, the action has access to the necessary secret and should not fail like it currently does on any foreign PR:
https://github.com/AlCalzone/node-zwave-js/pull/977/checks?check_run_id=1133804030

**Comment by ahmadnassri** [comment]
sounds reasonable, I'd say update this line to check both event types: https://github.com/ahmadnassri/action-dependabot-auto-merge/blob/13f9f5f54fd01d4614251de5a81b425cf0269f1f/action/lib/index.js#L15

and update the readme with default example to the new event with a note + link to alternative behavior

**Comment by AlCalzone** [comment]
I've investigated a bit more. Actually it would make more sense to not run the action at all for forks (since Dependabot always uses the actual repo):
```yml
# Automatically merge Dependabot PRs when version comparison is within the range
# that is configured in .github/auto-merge.yml

name: Auto-Merge Dependabot PRs

on:
  pull_request:

jobs:
  auto-merge:
    if: github.repository == 'AlCalzone/node-zwave-js' # <-- Notice this check!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR should be auto-merged
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
          # By default, squash and merge, so Github chooses nice commit messages
          command: squash and merge
```
