### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by Falcion** [ahmadnassri/action-dependabot-auto-merge#243]
<details>
<summary>Workflow file:
</summary>

```yaml
name: Auto-merge dependabot PRs

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
</details>

<details>
<summary>Workflow artifact:
</summary>

```powershell
Run ahmadnassri/action-dependabot-auto-merge@v2
/usr/bin/docker run --name ghcrioahmadnassriactiondependabotautomerge266_52e05[9](https://github.com/Falcion/UnitadeOBSIDIAN/actions/runs/7471182332/job/20331037419?pr=9#step:4:10) --label c03cd8 --workdir /github/workspace --rm -e "INPUT_TARGET" -e "INPUT_GITHUB-TOKEN" -e "INPUT_CONFIG" -e "INPUT_COMMAND" -e "INPUT_BOTNAME" -e "INPUT_APPROVE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/UnitadeOBSIDIAN/UnitadeOBSIDIAN":"/github/workspace" ghcr.io/ahmadnassri/action-dependabot-auto-merge:2.6.6
using workflow's "target": 
- match:
    dependency_type: all
    update_type: semver:minor

title: "build(deps-dev): bump markdownlint from 0.32.1 to 0.33.0"
depName: markdownlint
from: 0.32.1
to: 0.33.0
dependency type: development
security critical: false
config: all:semver:minor
all:semver:minor detected, will auto-merge
Error: Resource not accessible by integration
HttpError: Resource not accessible by integration
    at /action/node_modules/@octokit/request/dist-node/index.js:86:[21](https://github.com/Falcion/UnitadeOBSIDIAN/actions/runs/7471182332/job/20331037419?pr=9#step:4:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async approve (file:///action/lib/api.js:2:3)
    at async default (file:///action/lib/index.js:33:5)
    at async file:///action/index.js:53:1
```
</details>

What can cause this exception?

**Comment by ulfgebhardt** [comment]
I have the same Problem - any solution?

**Comment by Falcion** [comment]
Unfortunately, no. And as I see, this GitHub Action is no longer maintained.

Instead of this Action, I use [Auto Approve](https://github.com/marketplace/actions/auto-approve):

```yaml
name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
 ```
 
 > [!Note]
 > **I'm sorry that I have to advertise another project as part of this, if the maintainers don't like it, I can delete the comment.**
