### ISSUE TITLE
Auto-merge action doesn't work with digest updates

### ISSUE THREAD

**Issue by JustArchi** [ahmadnassri/action-dependabot-auto-merge#25]
Hey.

I believe that the action should be aware of digest versions, such as git submodules, or simply versions that do not follow semver for one reason or another.

Old dependabot assumed those to be on the level below `patch` updates: `major` > `minor` > `patch` > `digest`.

Right now the action simply fails to do anything with digest updates: **[example](https://github.com/JustArchiNET/ArchiSteamFarm/runs/1171359523?check_suite_focus=true#step:4:16)**. I do not expect from the action to do anything smart with versions that do not follow semver, but it'd be nice to enable auto-merge support for them. `minor` and `patch` targets should include `digest` by default, and `digest` should probably be added as yet another level to merge.

Thank you in advance for considering this enhancement.

**Comment by ahmadnassri** [comment]
isn't that satisfiable by setting `update_type: all`

https://github.com/ahmadnassri/action-dependabot-auto-merge#match-properties

**Comment by ahmadnassri** [comment]
also, do you have a reference to the "old" dependabot example of this? I don't believe i've come across this

**Comment by JustArchi** [comment]
@ahmadnassri I checked the code and various examples, the current code fails at interpreting the semver version because it expects all updates to be semver-compatible. Digest doesn't parse to a semver, and therefore the script is aborted, check my example above.

As of dependabot example, you can just add a git submodule to your project and make it update with auto-merging. They added digest update initially **[for docker](https://github.com/dependabot/dependabot-core/pull/100)**, but it's also being used in git submodules for example.

Example PR for auto-merging digest updates: https://github.com/JustArchiNET/ArchiSteamFarm/pull/1988

**Comment by JustArchi** [comment]
Also, I'd like to have a config similar to what I have right now in old dependabot, that is:
- all git submodules updates are merged
- only minor semver changes are merged for everything else

I'm fine with the config that specifies names of git submodules dependencies, as already possible in your example, but is that even possible?

```
- match:
    dependency_name: ASF-ui
    update_type: all

- match:
    update_type: semver:minor
```

**Comment by JustArchi** [comment]
Also, I believe that even without custom matches, the script should not throw at semver parsing, as it does right now. The ideal solution would be detecting that this is a `digest` update (which is easy, it just doesn't parse to a semver), and assume that to be included in all currently available targets, starting from `patch`. This is probably the least amount of work required to satisfy my use case, and it'd also work with all other types of dependabot updates that do not follow semver.

The question remains if above `match` block is valid, because I can totally see how somebody would not want to update some package in digest, yet want to have all other packages handled.

All of those should be valid:

```yaml
# This should have no effect, as semver:minor should include digests by default
- match:
    dependency_name: ASF-ui
    update_type: all

- match:
    update_type: semver:minor
```

```yaml
# This should be possible to disable auto-merge for a specific package, but still allow that for all other ones
- match:
    dependency_name: ASF-ui
    update_type: none

- match:
    update_type: semver:minor
```

```yaml
# We should also be able to merge only digest updates
- match:
    update_type: digest
```
