### ISSUE TITLE
Multiple Targets

### ISSUE THREAD

**Issue by ttshivers** [ahmadnassri/action-dependabot-auto-merge#4]
The current behavior is that the target must match exactly for the action to auto merge. For example, if you set target to `minor`, it will only auto merge minor PRs and not patch PRs. I could see this as being the intended behavior

The way I get it to work is by using the action multiple times.
```
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v1.1.0
        with:
          target: patch
      - uses: ahmadnassri/action-dependabot-auto-merge@v1.1.0
        with:
          target: minor
```

It works fine with invoking this action multiple times but would you consider adding the ability to add multiple targets or an option to make it auto merge PRs with versions less than or equal to target?
