### ISSUE TITLE
Manual merge required when using update_type: security:patch

### ISSUE THREAD

**Issue by Alexander-Betz** [ahmadnassri/action-dependabot-auto-merge#51]
Hello,

when I set update_type as `security:patch` the auto merging doesn't work and it says `manual merging required`. 

```
loaded merge config: 
# Fine-grained configuration

- match:
    dependency_type: all
    update_type: security:patch # includes patch updates!

title: "Bump axios from 0.21.0 to 0.21.1 in /npmfolder"
depName: axios
from: 0.21.0
to: 0.21.1
dependency type: production
security critical: false
config: all:security:patch
manual merging required
```

Here is how my workflow file looks like:

```
name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.mytoken }}
```

and here the config file:

```
# Fine-grained configuration

- match:
    dependency_type: all
    update_type: security:patch # includes patch updates!
```

Do you know what the problem could be? 
I saw someone else had the same problem a few months ago in this issue: https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/18. There it seemed to have been a problem with the version of the Github Action. I'm using `v2`. I also tried `v2.3.0` with no success.

Update: I saw now in the description of the action on the Github marketplace site that if the config is not `update_type: all` or `update_type: semver:all` the action falls back to manual merging. Can you explain to me why it's not possible for `security:patch`? Or will this be added in the future?

Thanks in advance!

**Comment by ahmadnassri** [comment]
it seems to think the dependency type is "production"....

I suspect this is coming from `semver`, I'll debug some more...

**Comment by ahmadnassri** [comment]
sorry for the delay, when I first read your issue, my brain was foggy ...

re-reading it now, your setting indicates only allow "security patches" to be auto merged. so it seems this is working as expected.

if you want something like "Bump axios from 0.21.0 to 0.21.1 in /npmfolder" to auto merge, then you should set the config to:

```yaml
- match:
    dependency_type: all
    update_type: security:patch # this will auto-merge PRs that are marked as "security " AND are versioned >= "patch"

- match:
    dependency_type: production
    update_type: semver:patch # this will auto-merge any PR that is a "production" dependency AND are versioned >= "patch"
```
