### ISSUE TITLE
"manual merge required" on semver:patch despite permission to semver:minor update_type

### ISSUE THREAD

**Issue by dnltsk** [ahmadnassri/action-dependabot-auto-merge#52]
Hi,

really wondering why the auto-merge action ends with a `manual merging required` message on an semver:path updatet_type, dispite the configuration to allow semver:minor update_types in `auto-merge.yml`.

`auto-merge.yml` file content is
```
- match:
      dependency_type: all
      update_type: semver:minor # includes patch updates!
```

`dependabot.yml` file content is
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
```

`.workflows/automerge-dependabot.yml` file content is
```
name: Auto-approve Dependabot
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@7782c7e2bdf62b4d79bdcded8332808fd2f179cd
        if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
```

Action's output is
```
using workflow's "target": 
- match:
    dependency_type: all
    update_type: 'semver:patch'

title: "Bump v8-to-istanbul from 7.0.0 to 7.1.0 in /cdk"
depName: v8-to-istanbul
from: 7.0.0
to: 7.1.0
dependency type: production
security critical: false
config: all:semver:patch
manual merging required
```

could a tiny typo or whitespace issue cause that anomaly?

**Comment by ahmadnassri** [comment]
it looks like your `auto-merge.yml` is not being read / found, and that's because you're not checking out the repo before running the action ...

more specifically, this:

```yaml
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
     
```

should be:


```yaml
  auto-merge:
    # see .github/auto-merge.yml for match configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
     
```

note the addition of `- uses: actions/checkout@v2`

replce with whatever your workflow checkout needs are, but this should work as is.
