### ISSUE TITLE
Error: Input required and not supplied: github-token

### ISSUE THREAD

**Issue by bennycode** [ahmadnassri/action-dependabot-auto-merge#68]
Since lately `ahmadnassri/action-dependabot-auto-merge@v2` fails in my project with the following error message:

```
Run ahmadnassri/action-dependabot-auto-merge@v2
/usr/bin/docker run --name ghcrioahmadnassriactiondependabotautomergev2_046a38
/action/node_modules/@actions/core/lib/core.js:94
        throw new Error(`Input required and not supplied: ${name}`);
              ^

Error: Input required and not supplied: github-token
    at Object.getInput (/action/node_modules/@actions/core/lib/core.js:94:15)
    at file:///action/index.js:28:15
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

Here is my setup:

```yml
- name: 'Automerge dependency updates from Dependabot'
  uses: ahmadnassri/action-dependabot-auto-merge@v2.4.0
  # Guarantee that commit comes from Dependabot (don't blindly trust external GitHub action checks)
  if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
  with:
    github-token: ${{ secrets.GH_TOKEN }}
```

Does `action-dependabot-auto-merge` internally uses `@actions/core`?

Luckily, my repository is public so I can point you to my build log file:
- https://github.com/bennycode/coinbase-pro-node/pull/457/checks?check_run_id=2262852364

And here is my workflow setup:
- https://github.com/bennycode/coinbase-pro-node/blob/main/.github/workflows/continuous-integration.yml
