### ISSUE TITLE
Auto-merge when target branch

### ISSUE THREAD

**Issue by WaKeMaTTa** [ahmadnassri/action-dependabot-auto-merge#77]
Can I auto merge only Pull Request that target a specific branch?

---

**Use case:**

I have `staging` branch I want all Pull Requests open by dependabot to be auto-merged when the CI (tests) is green.

**Comment by jotoeri** [comment]
This only runs the action, if the target branch is `main` ☺️ 
```
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.ref == 'refs/heads/main' &&
            (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_MERGE }}
```
