### ISSUE TITLE
Error: action triggered outside of a pull_request

### ISSUE THREAD

**Issue by pipedreambomb** [ahmadnassri/action-dependabot-auto-merge#94]
I'm trying to use this Action (and GitHub Actions in general) for the first time. 

I used the minimal set-up, but when I edit the .yml file, GitHub runs the action and it outputs `Error: action triggered outside of a pull_request`. 

Is this because it's supposed to only run when there's a new Dependabot PR? Is it working as intended? I'm just really confused if I've set it up right, or not.

**Comment by ahmadnassri** [comment]
can you share your github action workflow in which you added this action in? most likely it's being triggered on multiple events ..

**Comment by pipedreambomb** [comment]
I don't know, it's in a private repository, can I share that? If you just want the file, it looks like this:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE }}
```
Also, the latest build that ran automatically in response to a new Dependabot PR has a different error message:
```
/action/node_modules/@actions/core/lib/core.js:94
        throw new Error(`Input required and not supplied: ${name}`);
              ^

Error: Input required and not supplied: github-token
    at Object.getInput (/action/node_modules/@actions/core/lib/core.js:94:15)
    at file:///action/index.js:28:15
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```
